Repository wanted-team2/1week_productEnrollAdmin, pull requests merged in 2022-01, with the labels that each got.

#12 Feat: Box component 구현
  public/index.html
  src/components/base/Box/Box.jsx
  src/components/base/Box/Style.js
  src/components/base/index.js
  src/index.jsx
Labels: Feat

#14 :recycle: Refactor: checkTypeOfCss 함수 구현 및 BoxWrapper 컴포넌트에 적용
  src/components/base/Box/Style.js
  src/utils/functions/index.js
Labels: Refactor

#13 Feat: Button 컴포넌트 구현, globalStyle에 primary 컬러 기본값 추가
  src/components/base/Button/Button.jsx
  src/components/base/Button/Style.js
  src/components/base/index.js
  src/style/GlobalStyle.js
  src/utils/constants/index.js
Labels: Feat

#15 :recycle: Refactor: checkTypeOfCss 함수 적용 in ButtonWrapper
  src/components/base/Button/Style.js
Labels: Refactor

#17 :bug: Fix: 삭제된 logo192 import 오류 수정
  public/index.html
  public/manifest.json
Labels: Fix

#16 :sparkles: Feat: Input 컴포넌트 구현
  src/components/base/Input/Input.jsx
  src/components/base/Input/Style.js
  src/components/base/index.js
  src/style/theme.js
Labels: Feat

#18 :sparkles: Feat: Toggle 버튼, useToggle 훅 구현
  src/components/base/Toggle/Style.js
  src/components/base/Toggle/Toggle.jsx
  src/components/base/index.js
  src/hooks/index.js
  src/hooks/useToggle.js
Labels: Feat

#27 :sparkles: Feat: type, value, onChange props 추가 in Input 컴포넌트
  src/components/base/Input/Input.jsx
Labels: Feat

#22 :sparkles: Feat: Table, TableBody 컴포넌트 구현
  src/components/base/Table/Style.js
  src/components/base/Table/Table.jsx
  src/components/base/TableBody/Style.js
  src/components/base/TableBody/TableBody.jsx
  src/components/base/index.js
  src/style/GlobalStyle.js
  src/utils/constants/index.js
Labels: Feat

#25 :sparkles: Calendar 컴포넌트 구현
  src/components/base/Calendar/Calendar.jsx
  src/components/base/Calendar/Style.js
Labels: Feat

#21 ✨ Feat: DeleteButton 컴포넌트 구현
  src/components/base/DeleteButton/DeleteButton.jsx
  src/components/base/DeleteButton/Style.js
  src/components/base/index.js
Labels: Feat

#23 ✨ Feat: x버튼 들어있는 버튼 구현
  src/components/base/InnerDeleteButton/InnerDeleteButton.jsx
  src/components/base/InnerDeleteButton/Style.js
  src/components/base/index.js
Labels: Feat

#35 🐛 Fix: date 기본값 수정
  package.json
  src/components/base/Calendar/Calendar.jsx
  src/components/base/index.js
Labels: Fix

#34 Feat, Fix: AlertModal 구현, useModal return 값 변경
  src/components/base/Box/Style.js
  src/components/base/Button/Button.jsx
  src/components/base/Button/Style.js
  src/components/domain/AlertModal/AlertModal.jsx
  src/components/domain/AlertModal/Style.js
  src/components/domain/index.js
  src/hooks/useModal.js
Labels: Feat, Fix

#36 :recycle: Refactor: tbody 분기점 tr 태그 추가 in Table
  src/components/base/Table/Table.jsx
Labels: Refactor

#40 ✨ Feat: 상품 배송 설정, 상품 혜택 설정, 기타 설정 테이블 구현
  src/App.jsx
  src/components/base/Calendar/Calendar.jsx
  src/components/base/index.js
  src/components/table/ItemBenefitSetting/ItemBenefitSetting.jsx
  src/components/table/ItemDiliverySetting/ItemDiliverySetting.jsx
  src/components/table/ItemDiliverySetting/Style.js
  src/components/table/OtherSetting/OtherSetting.jsx
  src/components/table/index.js
  src/pages/ProductEnrollAdmin/ProductEnrollAdmin.jsx
Labels: Feat

#37 :sparkles: (Feat:노출 및 판매기간 설정, 상품 소개, 구매자 추천 테이블 구현)
  src/components/base/DeleteButton/DeleteButton.jsx
  src/components/base/DeleteButton/Style.js
  src/components/base/ImageItemList/ImageItemList.jsx
  src/components/base/ImageItemList/Style.js
  src/components/base/RadioButton/RadioButton.jsx
  src/components/base/TableBody/Style.js
  src/components/base/TableBody/TableBody.jsx
  src/components/base/index.js
  src/components/domain/index.js
  src/components/rows/ImagesADRows/ImagesADRows.jsx
  src/components/rows/SetExposurePeriodRow/SetExposurePeriodRow.jsx
  src/components/rows/index.js
  src/components/table/ProductImageTable/ProductImageTable.jsx
  src/components/table/RecommendImageTable/RecommendImageTable.jsx
  src/components/table/SetPeriodTable/SetPeriodTable.jsx
  src/components/table/SetPeriodTable/radioItems.js
  src/components/table/index.js
  src/utils/constants/index.js
  yarn.lock
Labels: Feat, Fix

#41 Feat: 상품 기본 정보 테이블 구현
  package.json
  public/tags.json
  src/components/base/Box/Style.js
  src/components/base/CheckBox/CheckBox.jsx
  src/components/base/ImageUploadButton/ImageUploadButton.jsx
  src/components/domain/FilterInput/FilterInput.jsx
  src/components/domain/ImageContainer/ImageContainer.jsx
  src/components/domain/TagList/Style.js
  src/components/domain/TagList/TagList.jsx
  src/components/domain/TagSearchModal/Style.js
  src/components/domain/TagSearchModal/TagSearchModal.jsx
  src/components/rows/CategoryRow/CategoryRow.jsx
  src/components/rows/CategoryRow/Style.js
  src/components/rows/TagRow/TagRow.jsx
  src/components/rows/index.js
  src/components/table/ProductionInformation/ProductionInformation.jsx
  src/components/table/ProductionInformation/Style.js
  src/hooks/useFetch.js
  src/utils/functions/index.js
Labels: Feat

#46 Feat: 옵션 추가, 추가옵션상품 추가, 업데이트 로직 구현 In OptionTable
  src/components/rows/OptionRow/AddOptionRow/AddOptionRow.jsx
  src/components/rows/OptionRow/OptionRow.jsx
  src/components/rows/OptionSetRow/OptionSetRow.jsx
  src/components/rows/OptionSetRow/Style.js
  src/components/table/OptionTable/OptionTable.jsx
  src/contexts/OptionContext/reducer.js
  src/contexts/OptionContext/types.js
  src/utils/functions/index.js
Labels: Feat

#48 :fire: Prune: 주석 제거 in OptionTable
  src/components/table/OptionTable/OptionTable.jsx
  src/contexts/OptionContext/reducer.js
Labels: Prune

#50 :recycle: Refactor: 안쓰는 코드 삭제, PropTypes 추가 in OptionTable 관련 컴포
  src/components/rows/OptionRow/AddOptionRow/AddOptionRow.jsx
  src/components/rows/OptionRow/OptionRow.jsx
  src/components/table/OptionTable/OptionTable.jsx
  src/components/table/OptionTable/Style.js
Labels: Refactor

#51 :sparkles: (Feat: 상품 정보 고시 테이블 구현)
  src/components/rows/InformationRow/AddInformationRow/AddInformationRow.jsx
  src/components/rows/InformationRow/InformationRow.jsx
  src/components/rows/InformationRow/Style.js
  src/components/rows/InformationSetRow/InformationSetRow.jsx
  src/components/rows/InformationSetRow/Style.js
  src/components/rows/index.js
  src/components/table/ItemInformationTable/ItemInformationTable.jsx
  src/components/table/ItemInformationTable/Style.js
  src/components/table/index.js
  src/contexts/InformationContext/InformationProvider.js
  src/contexts/InformationContext/reducer.js
  src/contexts/InformationContext/types.js
  src/contexts/OptionContext/reducer.js
  src/contexts/OptionContext/types.js
  src/index.jsx
Labels: Feat

#47 💄 상품 관리 페이지 레이아웃 구성
  src/components/base/Calendar/Calendar.jsx
  src/components/base/Gnb/Gnb.jsx
  src/components/base/Gnb/style.js
  src/components/base/Table/Style.js
  src/components/base/TableBody/Style.js
  src/components/base/Toggle/Style.js
  src/components/base/Toggle/Toggle.jsx
  src/components/base/index.js
  src/components/rows/SetExposurePeriodRow/SetExposurePeriodRow.jsx
  src/components/table/ItemBenefitSetting/ItemBenefitSetting.jsx
  src/components/table/ItemDiliverySetting/ItemDiliverySetting.jsx
  src/components/table/ItemDiliverySetting/Style.js
  src/components/table/OptionTable/OptionTable.jsx
  src/components/table/OtherSetting/OtherSetting.jsx
  src/components/table/ProductionInformation/ProductionInformation.jsx
  src/components/table/ProductionInformation/Style.js
  src/components/table/index.js
  src/pages/ProductEnrollAdmin/ProductEnrollAdmin.jsx
  src/pages/ProductEnrollAdmin/style.jsx
Labels: UI

#55 Feat, Refactor: 상대경로 -> 절대경로 수정, 요소 삭제 후 index 재조정 작업 추가, 상품 정보 고시 테이블 재구현
  src/components/base/Button/Button.jsx
  src/components/rows/InformationRow/AddInformationRow/AddInformationRow.jsx
  src/components/rows/InformationRow/InformationRow.jsx
  src/components/rows/InformationSetRow/InformationSetRow.jsx
  src/components/table/ItemInformationTable/ItemInformationTable.jsx
  src/contexts/InformationContext/InformationProvider.jsx
  src/contexts/InformationContext/reducer.js
  src/contexts/InformationContext/types.js
  src/contexts/OptionContext/OptionProvider.jsx
  src/contexts/OptionContext/reducer.js
  src/pages/ProductEnrollAdmin/ProductEnrollAdmin.jsx
  src/pages/ProductEnrollAdmin/Style.js
  src/utils/functions/index.js
Labels: Feat, Refactor
